Added tutorial for integrating gitops
litmuschaos/tutorials pull request #12
Opened 2021-10-04 15:47 UTC by Gbahdeyboh

Signed-off-by: Gbahdeyboh <gbahdeybohbello@gmail.com>

This is the tutorial for integrating Gitops in Litmus. 

Google Docs => https://docs.google.com/document/d/18Cx7ysPXDuYYFuGErPORREpKKhHySRMMb1C2L5avB9U/edit?usp=sharing

Codelabs => https://codelabs-preview.appspot.com/?file_id=18Cx7ysPXDuYYFuGErPORREpKKhHySRMMb1C2L5avB9U#0

2021-10-29 18:11 UTC, Gbahdeyboh commented
I've included both @gdsoumya.

2021-10-29 18:32 UTC, gdsoumya requested changes

2021-10-29 18:32 UTC, gdsoumya commented on tutorial-integrating-gitops/index.html
> +<p><strong>NOTE:</strong> If you intend to use ssh, it is recommended that you add your ssh GitHub URL instead of https.</p>
```suggestion
<p><strong>NOTE:</strong> If you intend to use ssh, it is necessary that you add your ssh GitHub URL instead of https.</p>
```

2021-10-29 18:32 UTC, gdsoumya commented on tutorial-integrating-gitops/index.html
> +<p><strong>NOTE:</strong> If you intend to use ssh, it is recommended that you add your ssh GitHub URL instead of https.</p>
Just a small change

2021-10-29 18:34 UTC, Gbahdeyboh commented
Done @gdsoumya .

2021-10-29 18:37 UTC, gdsoumya approved these changes

2021-10-29 18:38 UTC, gdsoumya commented
@rajdas98 @ksatchit if you are okay with the changes we can merge this

2021-11-01 08:35 UTC, rajdas98 approved these changes

2021-11-01 15:11 UTC, uditgaurav approved these changes

2021-11-01 15:12 UTC, merged