Fixes
litmuschaos/tutorials pull request #22
Opened 2021-11-08 16:25 UTC by Gbahdeyboh

Signed-off-by: Gbahdeyboh gbahdeybohbello@gmail.com

This PR fixes some basic issues across the whole tutorials. 

It fixes the following issues:

- #20 

(_Adding more_)

2021-11-15 20:05 UTC, Gbahdeyboh commented
@neelanjan00 @uditgaurav.

I have been taking a look at the Done button at the end of all the codelabs redirecting to a 404 page, but I've been unable to find a fix to it. It's a bit weird because it does not happen when I test the codelab using the Preview Code lab extension. It only happens after the code generation is done. 

I would have edited the code, but the"Done" button is not a part of the code. A huge chunk of the UI is injected by some codelabs JS script. 

I also had a look at the issues on the codelab repository, but couldn't quite find any issue around this specific problem. 

I think the best I can do now is to file a new issue on the codelabs repository and hopefully someone from their community fixes it.

2021-11-15 20:05 UTC, Gbahdeyboh commented
@neelanjan00 @uditgaurav.

I have been taking a look at the Done button at the end of all the codelabs redirecting to a 404 page, but I've been unable to find a fix to it. It's a bit weird because it does not happen when I test the codelab using the Preview Code lab extension. It only happens after the code generation is done. 

I would have edited the code, but the"Done" button is not a part of the code. A huge chunk of the UI is injected by some codelabs JS script. 

I also had a look at the issues on the codelab repository, but couldn't quite find any issue around this specific problem. 

I think the best I can do now is to file a new issue on the codelabs repository and hopefully someone from their community fixes it.

2021-11-16 22:54 UTC, Gbahdeyboh commented
@neelanjan00 can you lease review to see if the raised issues has been fixed?

2021-11-17 05:37 UTC, neelanjan00 requested changes

2021-11-17 05:37 UTC, neelanjan00 commented on tutorial-defining-steady-state-hypothesis/index.html
> +  <title>xDefining Steady State Hypothesis</title>
```suggestion
  <title>Defining Steady State Hypothesis</title>
```

2021-11-17 05:37 UTC, neelanjan00 commented on tutorial-defining-steady-state-hypothesis/index.html
> +                  title="xDefining Steady State Hypothesis"
```suggestion
                  title="Defining Steady State Hypothesis"
```

2021-11-17 05:38 UTC, neelanjan00 commented
LGTM, please fix these two typos then I will approve.

2021-11-17 05:38 UTC, neelanjan00 commented
You can also fix the DCO check @Gbahdeyboh

2021-11-24 09:44 UTC, Gbahdeyboh commented
I'm not sure why the DCO is not passing. My commits are signed-off

2021-11-24 10:32 UTC, closed without merging